### ISSUE TITLE
WakeUp Computer cmdlets fehlt

### ISSUE THREAD

**Issue by RaVen1322** [uwefranke/msgDSM7Module#1]
Ist es wirklich nur möglich beim cmdlet 'Install-DSM7ReinstallComputer' einen Computer per Wake-On-Lan aufzuwecken? Meine Skills reichen nicht, um mir ein eigenes cmdlet zu bauen das einen Computer lediglich aufwecken kann.

Enable-DSM7Computer -name "PC00001"
Enable-DSM7Computer -ID 534214

oder als Methode beim vorhandenen cmdlet 

$PC = Get-DSM7Computer -ID 534214 
$PC.WakeUp()

Wäre das über SOAP möglich?

**Comment by uwefranke** [comment]
Schon mal in den DSMC.log geschaut welcher SOAP Request ausgelöst wird? Wenn einer ausgelöst wird ist es möglich. Ich werde es mir mal anschauen, wenn ich wieder Zeit habe.

**Comment by uwefranke** [comment]
Version 1.0.2.3 Funktion WakeUp-DSM7Computer hinzugefügt.
