### ISSUE TITLE
Bitte Möglichkeit für SSL hinzufügen

### ISSUE THREAD

**Issue by malex-17** [uwefranke/msgDSM7Module#4]
Könnte man den Connect-Aufruf ein wenig abändern, damit er auch SSL unterstützt?
z.B. 

param (
		[System.String]$WebServer = "localhost",
		[System.String]$Port = "8080",
		[switch]$UseDefaultCredential = $false,
		[System.String]$User,
		[System.String]$UserPW,
		[switch]$UseSSL,
		$Credential
	)
	if($UseSSL){
		$protocol = "https"
		$port = "443"
	} else {
		$protocol = "http"
	}
	$DSM7wsdlURL = $protocol + "://" + $WebServer + ":" + $Port + "/blsAdministration/AdministrationService.asmx?WSDL"

**Comment by uwefranke** [comment]
bitte Version [1.0.2.9] (https://github.com/uwefranke/msgDSM7Module/releases/tag/1.0.2.9) testen, ich habe keine Möglichkeit es zu überprüfen im Moment

**Comment by malex-17** [comment]
Funktioniert einwandfrei!
Super Sache :-)

**Comment by uwefranke** [comment]
bitte nochmal mit [1.0.3.0] (https://github.com/uwefranke/msgDSM7Module/releases/tag/1.0.3.0) überprüfen, Port wieder änderbar:
`if ($UseSSL) {
		$Protocol = "https://"
		if (!$Port) { 
			$Port = "443"
		}
	}
	else {
		$Protocol = "http://"
		if (!$Port) { 
			$Port = "8080"
		}
	}
	`

**Comment by malex-17** [comment]
Funzt auch

**Comment by uwefranke** [comment]
closed with release  [1.0.3.1] (https://github.com/uwefranke/msgDSM7Module/releases/tag/1.0.3.1)
